spring.profiles.active: local

spring:
  h2:
    console:
      enabled: true
  datasource:
    url: jdbc:h2:file:~/test
    username: sa
    password:
    driver-class-name: org.h2.Driver

hystrix.command.default.circuitBreaker.sleepWindowInMilliseconds: 120000
hystrix.threadpool.default.metrics.rollingStats.timeInMilliseconds: 10
hystrix.command.default.circuitBreaker.requestVolumeThreshold: 1

cloud.aws.region.static: us-east-1
localstack:
  sqs:
    url: http://localhost:4576

